/* 사용자 */
DROP TABLE "MEMBER" 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE "BOARD" 
	CASCADE CONSTRAINTS;

/* 게시글 */
DROP TABLE "POST" 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE "REPLY" 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP SEQUENCE "SEQ_BOARD";

/* 게시글 */
DROP SEQUENCE "SEQ_POST";

/* 댓글 */
DROP SEQUENCE "SEQ_REPLY";

/* 게시글 그룹번호 */
DROP SEQUENCE "SEQ_POST_GN";

/* 게시판 */
CREATE SEQUENCE "SEQ_BOARD" 
	MINVALUE 1
	INCREMENT BY 1
	START WITH 1;

/* 게시글 */
CREATE SEQUENCE "SEQ_POST" 
	MINVALUE 1
	INCREMENT BY 1
	START WITH 1;

/* 댓글 */
CREATE SEQUENCE "SEQ_REPLY" 
	MINVALUE 1
	INCREMENT BY 1
	START WITH 1;

/* 게시글 그룹번호 */
CREATE SEQUENCE "SEQ_POST_GN" 
	MINVALUE 1
	INCREMENT BY 1
	START WITH 1;

/* 사용자 */
CREATE TABLE "MEMBER" (
	"MEM_ID" VARCHAR2(20) NOT NULL, /* 아이디 */
	"MEM_PASS" VARCHAR2(20) NOT NULL, /* 비밀번호 */
	"MEM_NAME" VARCHAR2(20) NOT NULL, /* 이름 */
	"MEM_EMAIL" VARCHAR2(30), /* 이메일 */
	"MEM_TEL" NUMBER, /* 전화번호 */
	"MEM_ADDR" VARCHAR2(100), /* 주소 */
	"MEM_BIRTH" DATE, /* 생일 */
	"GRADE" NUMBER(1,0) /* 등급 */
);

COMMENT ON TABLE "MEMBER" IS '사용자';

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '아이디';

COMMENT ON COLUMN "MEMBER"."MEM_PASS" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MEM_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEM_ADDR" IS '주소';

COMMENT ON COLUMN "MEMBER"."MEM_BIRTH" IS '생일';

COMMENT ON COLUMN "MEMBER"."GRADE" IS '등급';

CREATE UNIQUE INDEX "PK_MEMBER"
	ON "MEMBER" (
		"MEM_ID" ASC
	);

ALTER TABLE "MEMBER"
	ADD
		CONSTRAINT "PK_MEMBER"
		PRIMARY KEY (
			"MEM_ID"
		);

/* 게시판 */
CREATE TABLE "BOARD" (
	"BOARD_SEQ" NUMBER NOT NULL, /* 게시판 번호 */
	"BOARD_NAME" VARCHAR2(100) NOT NULL, /* 게시판 이름 */
	"MEM_ID" VARCHAR2(20) NOT NULL, /* 생성자 */
	"BOARD_LOC" NUMBER NOT NULL, /* 순서 */
	"BOARD_STAT" NUMBER(1,0) NOT NULL /* 사용 여부 */
);

COMMENT ON TABLE "BOARD" IS '게시판';

COMMENT ON COLUMN "BOARD"."BOARD_SEQ" IS '게시판 번호';

COMMENT ON COLUMN "BOARD"."BOARD_NAME" IS '게시판 이름';

COMMENT ON COLUMN "BOARD"."MEM_ID" IS '생성자';

COMMENT ON COLUMN "BOARD"."BOARD_LOC" IS '순서';

COMMENT ON COLUMN "BOARD"."BOARD_STAT" IS '사용 여부';

CREATE UNIQUE INDEX "PK_BOARD"
	ON "BOARD" (
		"BOARD_SEQ" ASC
	);

ALTER TABLE "BOARD"
	ADD
		CONSTRAINT "PK_BOARD"
		PRIMARY KEY (
			"BOARD_SEQ"
		);

/* 게시글 */
CREATE TABLE "POST" (
	"POST_SEQ" NUMBER NOT NULL, /* 게시글 번호 */
	"BOARD_SEQ" NUMBER NOT NULL, /* 게시판 번호 */
	"POST_NM" VARCHAR2(100) NOT NULL, /* 게시글 제목 */
	"POST_CONT" CLOB NOT NULL, /* 게시글 내용 */
	"MEM_ID" VARCHAR2(20) NOT NULL, /* 작성자 */
	"POST_REG" DATE NOT NULL, /* 작성 일시 */
	"POST_MOD" DATE, /* 수정 일시 */
	"POST_STAT" NUMBER(1,0) NOT NULL, /* 사용 여부 */
	"POST_GN" NUMBER NOT NULL, /* 그룹 번호 */
	"PAR_POST_SEQ" NUMBER /* 부모 게시글 번호 */
);

COMMENT ON TABLE "POST" IS '게시글';

COMMENT ON COLUMN "POST"."POST_SEQ" IS '게시글 번호';

COMMENT ON COLUMN "POST"."BOARD_SEQ" IS '게시판 번호';

COMMENT ON COLUMN "POST"."POST_NM" IS '게시글 제목';

COMMENT ON COLUMN "POST"."POST_CONT" IS '게시글 내용';

COMMENT ON COLUMN "POST"."MEM_ID" IS '작성자';

COMMENT ON COLUMN "POST"."POST_REG" IS '작성 일시';

COMMENT ON COLUMN "POST"."POST_MOD" IS '수정 일시';

COMMENT ON COLUMN "POST"."POST_STAT" IS '사용 여부';

COMMENT ON COLUMN "POST"."POST_GN" IS '그룹 번호';

COMMENT ON COLUMN "POST"."PAR_POST_SEQ" IS '부모 게시글 번호';

CREATE UNIQUE INDEX "PK_POST"
	ON "POST" (
		"POST_SEQ" ASC
	);

ALTER TABLE "POST"
	ADD
		CONSTRAINT "PK_POST"
		PRIMARY KEY (
			"POST_SEQ"
		);

/* 댓글 */
CREATE TABLE "REPLY" (
	"REPLY_SEQ" NUMBER NOT NULL, /* 댓글 번호 */
	"POST_SEQ" NUMBER NOT NULL, /* 게시글 번호 */
	"MEM_ID" VARCHAR2(20) NOT NULL, /* 작성자 */
	"REPLY_CONT" VARCHAR2(500) NOT NULL, /* 내용 */
	"REPLY_REG" DATE NOT NULL, /* 작성 일시 */
	"REPLY_MOD" DATE, /* 수정 일시 */
	"REPLY_STAT" NUMBER(1,0) NOT NULL, /* 사용 여부 */
	"PAR_REPLY_SEQ" NUMBER /* 부모 댓글 번호 */
);

COMMENT ON TABLE "REPLY" IS '댓글';

COMMENT ON COLUMN "REPLY"."REPLY_SEQ" IS '댓글 번호';

COMMENT ON COLUMN "REPLY"."POST_SEQ" IS '게시글 번호';

COMMENT ON COLUMN "REPLY"."MEM_ID" IS '작성자';

COMMENT ON COLUMN "REPLY"."REPLY_CONT" IS '내용';

COMMENT ON COLUMN "REPLY"."REPLY_REG" IS '작성 일시';

COMMENT ON COLUMN "REPLY"."REPLY_MOD" IS '수정 일시';

COMMENT ON COLUMN "REPLY"."REPLY_STAT" IS '사용 여부';

COMMENT ON COLUMN "REPLY"."PAR_REPLY_SEQ" IS '부모 댓글 번호';

CREATE UNIQUE INDEX "PK_REPLY"
	ON "REPLY" (
		"REPLY_SEQ" ASC
	);

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "PK_REPLY"
		PRIMARY KEY (
			"REPLY_SEQ"
		);

ALTER TABLE "BOARD"
	ADD
		CONSTRAINT "FK_MEMBER_TO_BOARD"
		FOREIGN KEY (
			"MEM_ID"
		)
		REFERENCES "MEMBER" (
			"MEM_ID"
		);

ALTER TABLE "POST"
	ADD
		CONSTRAINT "FK_BOARD_TO_POST"
		FOREIGN KEY (
			"BOARD_SEQ"
		)
		REFERENCES "BOARD" (
			"BOARD_SEQ"
		);

ALTER TABLE "POST"
	ADD
		CONSTRAINT "FK_MEMBER_TO_POST"
		FOREIGN KEY (
			"MEM_ID"
		)
		REFERENCES "MEMBER" (
			"MEM_ID"
		);

ALTER TABLE "POST"
	ADD
		CONSTRAINT "FK_POST_TO_POST"
		FOREIGN KEY (
			"PAR_POST_SEQ"
		)
		REFERENCES "POST" (
			"POST_SEQ"
		);

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "FK_REPLY_TO_REPLY"
		FOREIGN KEY (
			"PAR_REPLY_SEQ"
		)
		REFERENCES "REPLY" (
			"REPLY_SEQ"
		);

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "FK_POST_TO_REPLY"
		FOREIGN KEY (
			"POST_SEQ"
		)
		REFERENCES "POST" (
			"POST_SEQ"
		);

ALTER TABLE "REPLY"
	ADD
		CONSTRAINT "FK_MEMBER_TO_REPLY"
		FOREIGN KEY (
			"MEM_ID"
		)
		REFERENCES "MEMBER" (
			"MEM_ID"
		);